### ISSUE TITLE
Propose Logo

### ISSUE THREAD

**Issue by mirzazulfan** [tohodog/QSVideoPlayer#10]
Hi. I'm a graphic designer and an open source enthusiast. I would like to contribute to your awesome project by proposing logo design for it if you allow me. I'll be doing it as a gift for free to your awesome project.

**Comment by tohodog** [comment]
thanks!!i like it

**Comment by mirzazulfan** [comment]
Thanks for your response @tohodog .. what do you think about this ? 
![qs](https://user-images.githubusercontent.com/36124339/45016663-d7bb2200-b014-11e8-8777-9701f4b3d7b4.png)
If you need to change, please let me know. Best regard.

**Comment by tohodog** [comment]
I think this is better. I will add him as a logo for the next update. Thank you very much.

**Comment by mirzazulfan** [comment]
Thanks @tohodog . I'm glad you liked it. What color do you prefer ? i'll send you files and PR.

**Comment by mirzazulfan** [comment]
Hi, You can download all files [here](https://drive.google.com/drive/folders/1BHLi1judBcXqSzfbhS-yABPZbxWojRA_?ogsrc=32)
