### ISSUE TITLE
混淆需要加什么

### ISSUE THREAD

**Issue by dbq4130** [tohodog/QSVideoPlayer#15]

**Comment by tohodog** [comment]
#==========videoplayer==========
-dontwarn org.song.videoplayer.**
-keep class org.song.videoplayer.** { *; }

-dontwarn tv.danmaku.ijk.**
-keep class tv.danmaku.ijk.** { *; }

-dontwarn com.google.android.**
-keep class com.google.android.** { *; }
#==========videoplayer==========
