### ISSUE TITLE
解码器经过封装和设置么

### ISSUE THREAD

**Issue by hiliving** [tohodog/QSVideoPlayer#25]
我用过好几个封装ijk的播放器，播放如：http://iqiyi.qq-zuidazy.com/20190310/7025_cab66d66/index.m3u8
的视频就播不了，提示不支持协议，但是你的播放器可以播，请教在哪设置的？

**Comment by tohodog** [comment]
这个是直播流协议,安卓内置解码低版本不支持,ijk解码支持这个格式,可以使用
qsVideoView.setDecodeMedia(IjkMedia.class);

**Comment by tohodog** [comment]
ijk demo的设置参数我删了,我没设置什么参数,需要设置可以 demoVideoView.setUp(url, "这是个标题",null,List<IjkMeida.Option>);

**Comment by hiliving** [comment]
好吧，因为参考了其他项目的源码，没看出来啥区别，但是就是播不了
