### ISSUE TITLE
关于弹幕json文件每个字段的意义

### ISSUE THREAD

**Issue by fjm19960930** [tohodog/QSVideoPlayer#26]
请问弹幕json文件p字段下每个字符串的含义，谢谢

**Comment by tohodog** [comment]
"p": "14.810000419617,1,18,16777215,1484225491,0,fd3b921a,2839759733",

**Comment by fjm19960930** [comment]
啥是自定义参数时间戳，还有倒数第二个十六进制颜色是干啥的
