### ISSUE TITLE
本地缓存保存的时长

### ISSUE THREAD

**Issue by fjm19960930** [tohodog/QSVideoPlayer#27]
网络视频缓存到本地后是不是会保存一定时长然后就自动清除，这个时长可以设置吗

**Comment by tohodog** [comment]
只有设置缓存位置,缓存大小,缓存满了老的缓存会被挤出去,时长的话需要自己去扫描缓存文件夹,获取文件创建时间,自己管理
Proxy.setConfig(new HttpProxyCacheServer
                        .Builder(this)
                        .cacheDirectory(new File("/sdcard/video"))
                        //.fileNameGenerator() 存储文件名规则
                        .maxCacheSize(512 * 1024 * 1024)//缓存文件大小
                        //.maxCacheFilesCount(100)//缓存文件数目 二选一
        );
