### ISSUE TITLE
IjkExoMedia静音无效

### ISSUE THREAD

**Issue by 643063150** [tohodog/QSVideoPlayer#30]
IjkExoMedia静音无效 三星note8 vivonexs  小米5x 都不行，IjkMedia可以 但是识别的视频比例有问题

**Comment by tohodog** [comment]
IjkExoMedia不支持静音设置，IjkMedia比例问题能提供视频？

**Comment by 643063150** [comment]
比例问题就是视频是竖屏的但是他会识别成横屏，强制全屏也会是横屏然后把竖屏比例的视频画面裁剪
