### ISSUE TITLE
QSVideoPlayer跟webView一起使用，点击进入全屏显示有问题

### ISSUE THREAD

**Issue by Zhusyi** [tohodog/QSVideoPlayer#31]
QSVideoPlayer跟webView一起使用，点击进入全屏的时候，变成横屏显示了，然后播放变成暂停状态，再次点击全屏的时候，会进入全屏，但是所有控件包括页面都是放大一倍的样子。望解决

**Comment by tohodog** [comment]
能提供具体在webview里的使用代码吗
