### ISSUE TITLE
当视频比较短时(12秒视频)，拖动进度会重新播放

### ISSUE THREAD

**Issue by a582749382** [tohodog/QSVideoPlayer#40]
当视频比较短时(12秒视频)，拖动进度会重新播放，16秒的就正常播放

**Comment by tohodog** [comment]
这个可能和视频的关键帧缺失有关,跳转进度是跳转到最近的关键帧,比如5s间隔,跳12秒,实际会跳到10s.
ijk貌似可以配置支持,可以尝试下
        List<IjkMedia.Option> optionList = new ArrayList<>();
        IjkMedia.Option option = new IjkMedia.Option(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "enable-accurate-seek", 1);
        optionList.add(option);
        demoVideoView.setUp(QSVideo.Build("http:/xxx").option(optionList).build());
