### ISSUE TITLE
报错error -10000，0

### ISSUE THREAD

**Issue by jiaoheyan** [tohodog/QSVideoPlayer#44]
只用了本地mp4文件的url，点击按钮进行播放，报了上述错误

**Comment by tohodog** [comment]
连接呢 本地播放路径是这样的
file://sdcard/xx

**Comment by jiaoheyan** [comment]
> 
> 
> 连接呢 本地播放路径是这样的
> file://sdcard/xx

**Comment by jiaoheyan** [comment]
> 
> 
> 连接呢 本地播放路径是这样的
> file://sdcard/xx

还是不可以呀，主要是我用自带的videoview会报错MediaPlayer: error (1, -2147479551)才是用这个插件的
