### ISSUE TITLE
截图不能使用吗？

### ISSUE THREAD

**Issue by cctxwan** [tohodog/QSVideoPlayer#47]
我调用了截图方法 返回bitmap，但是发现没有什么用。是有什么注意事项吗？或者只能在全屏下使用？

**Comment by tohodog** [comment]
返回bitmap空的吗

**Comment by cctxwan** [comment]
是的  空字符串

**Comment by cctxwan** [comment]
这个是咋回事呢？？？

**Comment by tohodog** [comment]
你好,测试是可以的额,需要4.0以上系统

**Comment by cctxwan** [comment]
我手机是4.4.4的 拿不到bitmap



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 蔡小路 <notifications@github.com&gt;
发送时间: 2019年12月25日 12:47
收件人: tohodog/QSVideoPlayer <QSVideoPlayer@noreply.github.com&gt;
抄送: cctxwan <mr.cai_cai@foxmail.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[tohodog/QSVideoPlayer] 截图不能使用吗？ (#47)




你好,测试是可以的额,需要4.0以上系统
