### ISSUE TITLE
当把播放器放在DialogFragment里时全屏会出现冲突，希望能在非全屏状态但是布局时全屏的状态下能实现全屏状态下的功能

### ISSUE THREAD

**Issue by 643063150** [tohodog/QSVideoPlayer#55]
可能有点凹口 比如就是重力感应是在全屏状态下才有的，现在我的布局时全屏的 要是也能实现重力感应就好了

**Comment by tohodog** [comment]
emmm好像懂了,就是非全屏播放器也显示全屏的UI,你可以新建一个类继承DemoQSVideoView, 加一个方法去调用setStateAndMode(currentState, MODE_WINDOW_FULLSCREEN); 改变播放器的UI,因为这个方法是私有的

**Comment by 643063150** [comment]
> 

设置这个之后全屏时的功能如重力感应旋转屏幕也能在非全屏状态下生效吗

**Comment by tohodog** [comment]
自动旋转屏幕调用一下Util.SET_SENSOR(getContext()); 或者你的manifest配置文件设置即可

**Comment by 643063150** [comment]
> 自动旋转屏幕调用一下Util.SET_SENSOR(getContext()); 或者你的manifest配置文件设置即可

好的 我试一下 谢谢  主要这个播放器时放在了DialogFragment
